FROM tiangolo/meinheld-gunicorn-flask:python3.7-alpine3.8
COPY . /app
RUN pip install -r requirements.txt
#RUN pip uninstall -y enum34
ENV STATIC_PATH /app/{{cookiecutter.package_name}}/static
ENV MODULE_NAME {{cookiecutter.package_name}}
